spring.application.name=network-monitoring-system

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/network_monitoring_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true